source "https://rubygems.org"

# This includes the standard GitHub Pages plugins
gem "github-pages", group: :jekyll_plugins

# ✅ These must be listed to work with the theme
gem "jekyll-include-cache"
gem "jekyll-remote-theme"